const categories = [
  {
    id: "1",
    name: "Mode & Vêtements",
    slug: "mode-vetements",
    icon: "Shirt",
    color: "#E11D48",
    description: "Vêtements, mode et accessoires de fashion",
    productCount: 3420,
  },
  {
    id: "2",
    name: "Chaussures",
    slug: "chaussures",
    icon: "Footprints",
    color: "#7C3AED",
    description: "Chaussures pour hommes, femmes et enfants",
    productCount: 1850,
  },
  {
    id: "3",
    name: "Sacs & Accessoires",
    slug: "sacs-accessoires",
    icon: "ShoppingBag",
    color: "#DB2777",
    description: "Sacs à main, sacs à dos, ceintures et accessoires",
    productCount: 1230,
  },
  {
    id: "4",
    name: "Téléphones",
    slug: "telephones",
    icon: "Smartphone",
    color: "#C8102E",
    description: "Smartphones, téléphones portables et accessoires",
    productCount: 5670,
  },
  {
    id: "5",
    name: "Ordinateurs",
    slug: "ordinateurs",
    icon: "Laptop",
    color: "#4F46E5",
    description: "PC portables, ordinateurs de bureau et composants",
    productCount: 2890,
  },
  {
    id: "6",
    name: "Tablettes",
    slug: "tablettes",
    icon: "Tablet",
    color: "#6366F1",
    description: "Tablettes et accessoires",
    productCount: 980,
  },
  {
    id: "7",
    name: "Gaming",
    slug: "gaming",
    icon: "Gamepad2",
    color: "#8B5CF6",
    description: "Consoles, jeux vidéo et accessoires gaming",
    productCount: 1540,
  },
  {
    id: "8",
    name: "Télévisions",
    slug: "televisions",
    icon: "Tv",
    color: "#0EA5E9",
    description: "Téléviseurs, écrans et décodeurs",
    productCount: 1120,
  },
  {
    id: "9",
    name: "Audio",
    slug: "audio",
    icon: "Headphones",
    color: "#06B6D4",
    description: "Casques, enceintes, écouteurs et systèmes audio",
    productCount: 2340,
  },
  {
    id: "10",
    name: "Photo & Caméra",
    slug: "photo-camera",
    icon: "Camera",
    color: "#0891B2",
    description: "Appareils photo, caméras et accessoires",
    productCount: 870,
  },
  {
    id: "11",
    name: "Électroménager",
    slug: "electromenager",
    icon: "Refrigerator",
    color: "#059669",
    description: "Appareils électroménagers pour la cuisine et la maison",
    productCount: 2150,
  },
  {
    id: "12",
    name: "Maison",
    slug: "maison",
    icon: "Home",
    color: "#16A34A",
    description: "Articols de maison, linge de maison et rangement",
    productCount: 1680,
  },
  {
    id: "13",
    name: "Meubles",
    slug: "meubles",
    icon: "Armchair",
    color: "#15803D",
    description: "Meubles pour toutes les pièces de la maison",
    productCount: 1340,
  },
  {
    id: "14",
    name: "Décoration",
    slug: "decoration",
    icon: "Paintbrush",
    color: "#D97706",
    description: "Objets de décoration, tableaux et accessoires déco",
    productCount: 960,
  },
  {
    id: "15",
    name: "Bricolage",
    slug: "bricolage",
    icon: "Hammer",
    color: "#EA580C",
    description: "Outils, matériaux et fournitures de bricolage",
    productCount: 1450,
  },
  {
    id: "16",
    name: "Jardin",
    slug: "jardin",
    icon: "TreePine",
    color: "#166534",
    description: "Outillage jardin, plantes et aménagement extérieur",
    productCount: 670,
  },
  {
    id: "17",
    name: "Sport & Fitness",
    slug: "sport-fitness",
    icon: "Dumbbell",
    color: "#DC2626",
    description: "Équipements sportifs, fitness et activities de plein air",
    productCount: 1890,
  },
  {
    id: "18",
    name: "Vélos",
    slug: "velos",
    icon: "Bike",
    color: "#CA8A04",
    description: "Vélos, vélos électriques et accessoires",
    productCount: 520,
  },
  {
    id: "19",
    name: "Motos",
    slug: "motos",
    icon: "Bike",
    color: "#B91C1C",
    description: "Motos, scooters et accessoires",
    productCount: 2100,
  },
  {
    id: "20",
    name: "Voitures",
    slug: "voitures",
    icon: "Car",
    color: "#1D4ED8",
    description: "Voitures neuves et occasion",
    productCount: 1760,
  },
  {
    id: "21",
    name: "Pièces automobiles",
    slug: "pieces-automobiles",
    icon: "Cog",
    color: "#4338CA",
    description: "Pièces détachées et accessoires automobiles",
    productCount: 1320,
  },
  {
    id: "22",
    name: "Immobilier",
    slug: "immobilier",
    icon: "Building2",
    color: "#7C2D12",
    description: "Terrains, maisons, appartements et locaux commerciaux",
    productCount: 3210,
  },
  {
    id: "23",
    name: "Livres",
    slug: "livres",
    icon: "BookOpen",
    color: "#92400E",
    description: "Livres, romans, manuels et BD",
    productCount: 780,
  },
  {
    id: "24",
    name: "Musique",
    slug: "musique",
    icon: "Music",
    color: "#A21CAF",
    description: "Disques, vinyles et instruments de musique",
    productCount: 430,
  },
  {
    id: "25",
    name: "Instruments de musique",
    slug: "instruments-musique",
    icon: "Guitar",
    color: "#C026D3",
    description: "Guitares, pianos, percussions et accessoires",
    productCount: 560,
  },
  {
    id: "26",
    name: "Beauté & Bien-être",
    slug: "beaute-bienetre",
    icon: "Sparkles",
    color: "#EC4899",
    description: "Cosmétiques, soins et produits de beauté",
    productCount: 2450,
  },
  {
    id: "27",
    name: "Montres & Bijoux",
    slug: "montres-bijoux",
    icon: "Watch",
    color: "#D946EF",
    description: "Montres, bijoux et accessoires de luxe",
    productCount: 1670,
  },
  {
    id: "28",
    name: "Bébés & Jouets",
    slug: "bebes-jouets",
    icon: "Baby",
    color: "#F472B6",
    description: "Articles bébé, jouets et puériculture",
    productCount: 1120,
  },
  {
    id: "29",
    name: "Animaux",
    slug: "animaux",
    icon: "PawPrint",
    color: "#A3E635",
    description: "Animaux de compagnie, accessoires et nourriture",
    productCount: 340,
  },
  {
    id: "30",
    name: "Matériel professionnel",
    slug: "materiel-professionnel",
    icon: "Briefcase",
    color: "#475569",
    description: "Équipements et matériel professionnel",
    productCount: 890,
  },
  {
    id: "31",
    name: "Services",
    slug: "services",
    icon: "Wrench",
    color: "#64748B",
    description: "Services proposés par des professionnels",
    productCount: 1560,
  },
  {
    id: "32",
    name: "Divers",
    slug: "divers",
    icon: "Package",
    color: "#78716C",
    description: "Autres articles et objets divers",
    productCount: 2780,
  },
];

export default categories;

export const getCategoryBySlug = (slug) =>
  categories.find((c) => c.slug === slug);

export const getCategoryById = (id) =>
  categories.find((c) => c.id === id);

export const getCategorySlugs = () =>
  categories.map((c) => c.slug);
